name: "Workflow 2 - Output events on `issues`"
on: 
  issues:
    types: [opened, edited, milestoned]
jobs:
  Echo:
    runs-on: ubuntu-latest
    steps:
      - name: output via shell
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: issue event with github context
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
